### PR TITLE
Modified the script to be a module for ease of deployment

### PR DESCRIPTION
**Pull request by c-wilkinson**
Initial changes to make the script a publishable module, so it's a bit easier to deploy on various machines.

### CODE REVIEW

**Comment by brasmith-ms** [comment]
Hi @c-wilkinson, thanks for the contribution! I like the idea you have here, but since this is meant to be a sample script for Windows Sandbox we'd like to keep it to just a single script. This makes it easier for people to just download a single file to get up and running quickly.

**Comment by c-wilkinson** [comment]
Sure, I can do that this evening when I get finish work.

**Comment by c-wilkinson** [comment]
In fact, it was a smaller job than expected so knocked it out just now.  I've tested by running: -

```cls; 
Remove-Variable * -ErrorAction SilentlyContinue; 
Remove-Module *; 
$error.Clear();
Import-Module "E:\GitHub\Windows-Sandbox-Utilities\Folding In Sandbox\Module\FAHSandbox.psm1" -Prefix MS;

MSStart;
```

Which successfully started up the F@H Sandbox.

**Comment by brasmith-ms** [comment]
Looks good to me, thank you!

**Pull request merged**
